kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: repl-sc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
